### ISSUE TITLE
Too many supernodes ERROR with V2.9.0_r747 on Win10

### ISSUE THREAD

**Issue by olivierolejniczak** [lucktu/n2n#6]
Any idea why I get the following error?

C:\n2n\n2n_v3_windows_x64_v2.9.0_r747_static_by_Tim\x64>edge.exe -a 10.10.10.1 -c 111 -k 123 -l n2n.lucktu.com:10086
27/Jan/2021 18:36:00 [n2n.c:278] WARNING: Failed to resolve supernode host n2n.lucktu.com
27/Jan/2021 18:36:00 [edge_utils.c:2764] WARNING: Invalid socket
27/Jan/2021 18:36:00 [edge.c:405] WARNING: Too many supernodes!

C:\n2n\n2n_v3_windows_x64_v2.9.0_r747_static_by_Tim\x64>pause
Appuyez sur une touche pour continuer...

**Comment by Logan007** [comment]
The real underlying issue is the failing name resolution as indicated too lines above `27/Jan/2021 18:36:00 [n2n.c:278] WARNING: Failed to resolve supernode host n2n.lucktu.com`. For whatever reason the name resolution does not work as expected.

The `Too many supernodes!` message is a wording error which I have just fixed in [this pull request](https://github.com/ntop/n2n/pull/634).

**Comment by lucktu** [comment]
Sorry the program here comes from the net friend, I can not be responsible for its correctness,

If you have a problem, try compiling it yourself, or use the latest program.
